version: "2"

services:
  apis:
    image: thanhson1085/api-seed
    depends_on:
      - db
      - redis
    networks:
      - front-net
      - back-net

  site:
    image: thanhson1085/site-seed
    networks:
      - front-net

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - back-net

  db:
    image: mongo:3.2
    container_name: db
    volumes:
        - "mongodb:/data/db"
    networks:
      - back-net

  gateway:
    image: nginx
    container_name: gateway
    volumes:
      - ./app.template:/etc/nginx/conf.d/default.conf
      - ./nginx.template:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apis
    networks:
      - front-net

volumes:
    mongodb:
    apis:
networks:
  front-net:
  back-net:
