version: "2"

services:
  nginx:
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.nginx"
    depends_on:
      - users
      - apps
      - broker
      - fluentd
    networks:
      - front-net
      - proxy-net
      - monitor-net

  kibana:
    image: kibana
    volumes:
      - ./monitor/kibana/kibana.yml:/etc/kibana/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - monitor-net

  fluentd:
    build: ./monitor/fluentd/.
    image: registry.gitlab.com/thanhson1085/koor:fluentd
    ports:
      - "24224:24224"
    depends_on:
      - elasticsearch
    environment:
      - ES_PORT_9200_TCP_ADDR=elasticsearch
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    volumes:
      - "grafana:/var/lib/grafana"
    environment:
      - GF_SERVER_ROOT_URL=https://monitor.koor.io
      - GF_SECURITY_ADMIN_PASSWORD=Koor.10
    networks:
      - monitor-net

  kapacitor:
    image: kapacitor
    depends_on:
      - influxdb
    volumes:
      - ./monitor/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - "kapacitor:/var/lib/kapacitor"
    networks:
      - monitor-net

  influxdb:
    image: influxdb 
    networks:
      - monitor-net
    volumes:
        - "influxdb:/var/lib/influxdb"
    networks:
      - monitor-net

  telegraf:
    image: telegraf
    hostname: nodeone
    depends_on:
      - influxdb
    environment:
      - "HOST_PROC=/rootfs/proc"
      - "HOST_SYS=/rootfs/sys"
      - "HOST_ETC=/rootfs/etc"
    volumes:
      - ./monitor/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    networks:
      - monitor-net
        
volumes:
    influxdb:
    kapacitor:
    grafana:
