version: "2"

services:
  users:
    build: ./users
    image: registry.gitlab.com/thanhson1085/koor/users
    environment:
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      MAILER_AUTH_PASS: ${MAILER_AUTH_PASS}
      MAILER_AUTH_USER: ${MAILER_AUTH_USER}
    depends_on:
      - db
      - redis
    networks:
      - front-net
      - back-net

  apps:
    build: ./apps
    image: registry.gitlab.com/thanhson1085/koor/apps
    depends_on:
      - db
      - redis
    environment:
      MAILER_AUTH_PASS: ${MAILER_AUTH_PASS}
      MAILER_AUTH_USER: ${MAILER_AUTH_USER}
    networks:
      - front-net
      - back-net

  site:
    build: ./site
    image: registry.gitlab.com/thanhson1085/koor/site
    networks:
      - front-net

  land:
    build: ./land
    image: registry.gitlab.com/thanhson1085/koor/land
    networks:
      - front-net

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - back-net

  db:
    image: mongo:3.2
    container_name: db
    volumes:
        - "mongodb:/data/db"
    networks:
      - back-net

  gateway:
    image: nginx
    container_name: gateway
    volumes:
      - ./app.template:/etc/nginx/conf.d/default.conf
      - ./nginx.template:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apps
      - users
    networks:
      - front-net

volumes:
    mongodb:
networks:
  front-net:
  back-net:
