swagger: '2.0'
info:
    title: App API
    description: Happy to code App API
    version: '1.0.0'
schemes:
    - http
basePath: /
produces:
    - application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
    /api/v1/projects/create:
        post:
            summary: Create a new project account
            description: |
                Create a new project account
            parameters:
                - name: data
                  in: body
                  description: json body data to create new project
                  required: true
                  schema:
                      required:
                          - name
                      properties:
                          name:
                              type: string
                              description: Project Name
                          fileId:
                              type: string
                              description: File Id
                          albumId:
                              type: string
                              description: Album Id
                          description:
                              type: string
                              description: Description
            responses:
                200:
                    description: Returns a access token
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Projects

    /api/v1/projects/update/{id}:
        put:
            summary: Update project
            description: |
                Update a projec
            parameters:
                - name: id
                  in: path
                  description: Project Id
                  required: true
                  type: string
                  format: string
                - name: data
                  in: body
                  description: json body data
                  required: true
                  schema:
                      required:
                          - name
                          - fileId
                          - description
                          - albumId
                      properties:
                          name:
                              type: string
                              description: Project Name
                          fileId:
                              type: string
                              description: File Id
                          albumId:
                              type: string
                              description: Album Id
                          description:
                              type: string
                              description: Description
            responses:
                200:
                    description: Returns a access token
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Projects

    /api/v1/projects/delete/{id}:
        delete:
            summary: Delete a project
            description: |
                Delete a project by Id
            security:
                - Bearer: []
            parameters:
                - name: id
                  in: path
                  description: Project Id
                  required: true
                  type: string
                  format: string
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Projects

    /api/v1/projects/get/{id}:
        get:
            summary: Get a project
            description: |
                Get a project by Id
            security:
                - Bearer: []
            parameters:
                - name: id
                  in: path
                  description: Project Id
                  required: true
                  type: string
                  format: string
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Projects

    /api/v1/projects/list/{page}/{limit}:
        get:
            summary: Get list of project
            description: |
                Get list of project with page and limit
            security:
                - Bearer: []
            parameters:
                - name: page
                  in: path
                  description: Page Number
                  required: true
                  type: string
                  default: 1
                - name: limit
                  in: path
                  description: Limit Number
                  required: true
                  type: string
                  default: 10
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Projects

    /api/v1/devices/list/{projectId}/{page}/{limit}:
        get:
            summary: Get list of project
            description: |
                Get list of project with page and limit
            security:
                - Bearer: []
            parameters:
                - name: projectId
                  in: path
                  description: Project id
                  required: true
                  type: string
                - name: page
                  in: path
                  description: Page Number
                  required: true
                  type: string
                  default: 1
                - name: limit
                  in: path
                  description: Limit Number
                  required: true
                  type: string
                  default: 10
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Devices

    /api/v1/devices/create:
        post:
            summary: Create a new device
            description: |
                Create a new device
            parameters:
                - name: data
                  in: body
                  description: json body data to create new device
                  required: true
                  schema:
                      required:
                          - name
                          - projectId
                      properties:
                          name:
                              type: string
                              description: Device Name
                          projectId:
                              type: string
                              description: Project ID
                          description:
                              type: string
                              description: Device Description
                          fileId:
                              type: string
                              description: File ID
                          albumId:
                              type: string
                              description: Album ID
                          address:
                              type: string
                              description: Description
                          lat:
                              type: number
                              format: float
                              description: Latitude
                          long:
                              type: number
                              format: float
                              description: Longtitude
            responses:
                200:
                    description: Returns a access token
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Devices

    /api/v1/devices/delete/{id}:
        delete:
            summary: Delete a device
            description: |
                Delete a device by Id
            security:
                - Bearer: []
            parameters:
                - name: id
                  in: path
                  description: Device Id
                  required: true
                  type: string
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Devices

    /api/v1/devices/get/{id}:
        get:
            summary: Get a device
            description: |
                Get a device by Id
            security:
                - Bearer: []
            parameters:
                - name: id
                  in: path
                  description: Device Id
                  required: true
                  type: string
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Devices

    /api/v1/devices/update/{id}:
        put:
            summary: Update a Device
            description: |
                Update a device
            parameters:
                - name: id
                  in: path
                  description: Device Id
                  required: true
                  type: string
                - name: data
                  in: body
                  description: json body data to create new device
                  required: true
                  schema:
                      required:
                          - name
                          - description
                          - fileId
                          - albumId
                      properties:
                          name:
                              type: string
                              description: Device Name
                          description:
                              type: string
                              description: Device Description
                          fileId:
                              type: string
                              description: File ID
                          albumId:
                              type: string
                              description: Album ID
            responses:
                200:
                    description: Returns a access token
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Devices
