swagger: '2.0'
info:
    title: File API
    description: Happy to code File API
    version: '1.0.0'
schemes:
    - http
basePath:
produces:
    - application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
    /api/v1/upload/images:
        post:
            summary: Upload Images
            description: |
                Upload Images
            parameters:
                - name: file
                  in: formData
                  description: Files
                  required: true
                  type: file
            responses:
                200:
                    description: Returns a access token
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Files

    /api/v1/files/get/{id}:
        get:
            summary: Get a file
            description: |
                Get a file by Id
            security:
                - Bearer: []
            parameters:
                - name: id
                  in: path
                  description: File Id
                  required: true
                  type: string
                  format: string
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Files

    /api/v1/files/getByIds/{ids}:
        get:
            summary: Get files by ids
            description: |
                Get a files by ids
            security:
                - Bearer: []
            parameters:
                - name: ids
                  in: path
                  description: File Ids
                  required: true
                  type: string
                  format: string
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Files

    /api/v1/files/getAlbum/{id}:
        get:
            summary: Get a Album Details
            description: |
                Get a Album Details
            security:
                - Bearer: []
            parameters:
                - name: id
                  in: path
                  description: Album Id
                  required: true
                  type: string
                  format: string
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Files

    /api/v1/notifications/list/{page}/{limit}:
        get:
            summary: Get list of notifications
            description: |
                Get list of notifications with page and limit
            security:
                - Bearer: []
            parameters:
                - name: page
                  in: path
                  description: Page Number
                  required: true
                  type: string
                  default: 1
                - name: limit
                  in: path
                  description: Limit Number
                  required: true
                  type: string
                  default: 10
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Notifications

    /api/v1/feeds/list/{page}/{limit}:
        get:
            summary: Get User Feed
            description: |
                Get User Feed
            security:
                - Bearer: []
            parameters:
                - name: page
                  in: path
                  description: Page Number
                  required: true
                  type: string
                  default: 1
                - name: limit
                  in: path
                  description: Limit Number
                  required: true
                  type: string
                  default: 10
            responses:
                200:
                    description: OK
                401:
                    description: Unauthorized
                400:
                    description: Bad Request
                406:
                    description: Not Acceptable
                500:
                    description: Server Internal error
            tags:
                - Feeds
